# Generated by Django 4.1.3 on 2022-11-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='county',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='town',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='service', to='customer.serviceitem'),
        ),
    ]
