# Generated by Django 4.1.3 on 2022-11-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_servicemodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
