# Generated by Django 4.1.3 on 2022-11-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_servicemodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
