# Generated by Django 4.1.3 on 2022-11-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_servicemodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
