# Generated by Django 4.1.3 on 2022-11-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_servicemodel_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='is_accepted',
        ),
    ]
